name = "NeperStructureGenerator"
uuid = "149900c0-240c-4222-87c1-7808fe3d6070"
authors = ["Said Harb"]
version = "0.1.0"

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
